### ISSUE TITLE
Reading dat files generated from GNU Radio Companion

### ISSUE THREAD

**Issue by Infiltra** [Numerix-DSP/siglib#2]
So I generated a .dat file from GNU Radio Companion, and I wanted to use siglib's API to do some DSP and visualization tasks with it. For this end just for practicing I use the example in FileIO test_dat.c, modified it a little bit, and used my file as input. This is not giving me any output, and I have no idea why it is happening this way, any idea on this problem would be of great help to me. For your reference, I'll paste the code and please tell me a way on how I can attach a .dat file to this post.
```
// test dat and bin fileIO

// Include files
#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<siglib.h>

// Constants
#define IO_LENGTH   1024
#define SAMPLE_LENGTH   10000

// Declare global variables 
SLData_t inputData[SAMPLE_LENGTH];


int main(void){
    SLArrayIndex_t SampleCount;
    SLData_t sampleRate = 32000;
    SLArrayIndex_t sampleIndex = 0l;
    FILE *fpInputFile;
    printf("Opening input test file\n");
    if ((fpInputFile = fopen("SineSample.dat", "rb")) == NULL)
    {
        /* code */
        printf("Error opening input .dat file \n");
        exit(-1);
    }
    sampleRate = SUF_DatReadHeader(fpInputFile);
    printf("Sample Rate=%lf \n", sampleRate);
    // SampleCount = (int)SUF_DatReadData (inputData, fpInputFile, IO_LENGTH);
    while ((SampleCount = (int)SUF_DatReadData (inputData, fpInputFile, IO_LENGTH)) == IO_LENGTH) {
        for (int i = 0; i < SampleCount; i++){
            printf ("%lf, ", inputData[i]);
        }
    }

    fclose (fpInputFile);
    printf ("\n\n");

    return (0);
    
}
```

**Comment by Infiltra** [comment]
Follow up: The sample rate from the header is read as 0.00 and no data is read from the file.

**Comment by johned0** [comment]
SigLib .dat file format is text.
I've googled to find the GNURadio .dat file format and documentation but couldn't find much. It appears that it is binary.
You could try SUF_BinReadData() but I suspect there might be more to the .dat than just raw binary data.
Alternatively you could see if GNURadio includes a function for reading a .dat into a C floating point array.
Best,
John

**Comment by Infiltra** [comment]
@johned0 Thank you I'll try that, till that point I'll close this thread, if the problem persist I shall reopen it again.
