### ISSUE TITLE
Wrong path in SetEnv.bat

### ISSUE THREAD

**Issue by Andinni** [Numerix-DSP/siglib#3]
Hi, 
Just starting to try out the siglib library. 
Apologies if this is not the preferred channel to communicate about the library. 
I think there migth be a glitch in SetEnv.bat, line 22:
`set LIB=%LIB%;%SIGLIB_PATH%\lib\Microsoft\static_library\Release;C:\portaudio_v19\build\msvc\Win32\Release`

Shouldn't this rather be:  
`set LIB=%LIB%;%SIGLIB_PATH%\lib\Microsoft\siglib_32\static_library\Release;C:\portaudio_v19\build\msvc\Win32\Release`
?
(with the siglib_32 in the middle?)
thank you

**Comment by johned0** [comment]
Hi Andinni,
I'm more than happy for your to ask on here.
The 32 bit Microsoft build of SigLib is no longer tested, only 64 bit so we recommend using the 64 bit library, with the default version of the environment variable.
If you do need to use the 32 bit library then your second version of the environment variable is correct.
Best regards,
John
