### ISSUE TITLE
Compilation issue on the newest version: Cannot find several function defined from the function list

### ISSUE THREAD

**Issue by Sean-Melchizedek** [Numerix-DSP/siglib#5]
I‘ve tried compiling the newest version(10.55) from the SWIG version.
However, I've found the following function cannot be found:

SDS_OnePoleTimeConstantToFilterCoeff
SDS_OnePoleCutOffFrequencyToFilterCoeff
SDS_OnePoleHighPassCutOffFrequencyToFilterCoeff
SUF_WavReadInt
SUF_WavWritInt
SUF_StrError

These functions can be found in the official siglib reference manual, but can not be compiled via SWIG and I also failed to call them from the simple VS2022 MSVC compiled one.

```
Siglib_test.obj : error LNK2019: Unresolved external symbol SUF_StrError referenced in function main
Siglib_test.obj : error LNK2019: Unresolved external symbol __imp_SUF_WavReadInt referenced in function main
Siglib_test.obj : error LNK2019: Unresolved external symbol __imp_SUF_WavWriteInt referenced in function main
Siglib_test.obj : error LNK2019: Unresolved external symbol SDS_OnePoleTimeConstantToFilterCoeff referenced in function main
Siglib_test.obj : error LNK2019: Unresolved external symbol SDS_OnePoleCutOffFrequencyToFilterCoeff referenced in function main
Siglib_test.obj : error LNK2019: Unresolved external symbol SDS_OnePoleHighPassCutOffFrequencyToFilterCoeff referenced in function main
```

It confuses me because I can see these functions from the source file iirfilt.c and the MSVC version is compiled successfully with zero error.
![image](https://github.com/user-attachments/assets/2614ce76-dbca-48e4-8396-0a6c46d4514c)

**Comment by johned0** [comment]
Thanks for this.
I'm unable to replicate so please can you let me know exactly what you are doing ?
John

**Comment by johned0** [comment]
WavReadInt and SUF_WavWriteInt problems found and library updated.
Can't replicate the others.
Please feel free to share exactly what you are doing to allow me to replicate the other issues.
Thanks,
J

**Comment by Sean-Melchizedek** [comment]
John,
Sorry for the late reply and thanks for your quick update!
I was trying to compile siglib via SWIG to use siglib functions from Java. 
I failed to use the default script in  siglib-main\SWIG\swigjava.bat, as SUF_WavReadInt
SUF_WavWritInt cannot be found from the source. 
And sorry again for my confusing descriptions. 😭

**Comment by Sean-Melchizedek** [comment]
> WavReadInt and SUF_WavWriteInt problems found and library updated. Can't replicate the others. Please feel free to share exactly what you are doing to allow me to replicate the other issues. Thanks, J

Really appreciate the quick fix, I will definitely try the updated library.
Thanks again!

**Comment by johned0** [comment]
No worries, Sean,
Thanks for the update.
J
